name: fftcg_companion_app
description: A companion app for Final Fantasy Trading Card Game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  workmanager: ^0.5.1
  flutter_staggered_grid_view: ^0.7.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.4
  logging: ^1.2.0    
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.3.4
  firebase_app_check: 0.3.1+7
  connectivity_plus: ^6.1.0
  flutter_launcher_icons: ^0.14.2
  internet_connection_checker: ^1.0.0+1
  firebase_crashlytics: ^4.2.0
  device_info_plus: ^9.1.1
  google_api_availability: 5.0.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.3.4
  shared_preferences_android: 2.3.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.14
  json_serializable: ^6.7.1
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  

flutter:
  uses-material-design: true


flutter_launcher_icons:
  image_path: "fftcg_card_icon.png"
  android: true
  ios: true